### ISSUE TITLE
omg

### ISSUE THREAD

**Issue by kieranjol** [BAM-PFA/edith#34]
This looks incredible!!!!!!!!!!!!!!!!!!

**Comment by mcampos-quinn** [comment]
Haha, thanks! It's working so far, but it's def an iterative process.

**Comment by kieranjol** [comment]
So is the idea here that each user hosts an instance of edith on their computer and the pymm processes launch locally, but they're feeding into external databases? Or is there a central EDITH server and all files are uploaded there and processed?

**Comment by mcampos-quinn** [comment]
EDITH is hosted on a Linux  server on our network that we bought specifically to handle transcoding video. Files/directories of files are sent to a shared folder on the server and users can select to ingest from there. Pymm is run by EDITH on the assets and the Pymm database is hosted on the server too. The film collection database (and potentially other descriptive data sources) is also on the network and it gets queried during the ingest process by parsing the file/dir name. The ltfs interface is also on the EDITH server, which has PCIe scsi interfaces for the lto decks. And EDITH also hosts resourcespace, which we're using as a front end for access copies and metadata (including which lto tape a master resides on). 😬

**Comment by alexharris** [comment]
EDITH does it all!

**Comment by mcampos-quinn** [comment]
Lol sup lurker!

**Comment by alexharris** [comment]
Its not my fault I receive an email notification for every comment

**Comment by mcampos-quinn** [comment]
:'(
